---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: '... hay un botón que dice _"Enviar"_;'
  checked: true
- value: '... _"Antes de empezar"_ es un link;'
  checked: false
- value: "... hay un link a la página principal de Mumuki."
  checked: true
name: Antes de empezar
